"""empty message

Revision ID: 6e3bf4d31e52
Revises: 74f5266a7ce8
Create Date: 2021-05-20 08:21:30.884689

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e3bf4d31e52'
down_revision = '74f5266a7ce8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', '_password')
    op.drop_column('user','note')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('_password', mysql.VARCHAR(length=80), nullable=False))
    # ### end Alembic commands ###
