"""empty message

Revision ID: 9f3c04ef3e09
Revises: 6e3bf4d31e52
Create Date: 2021-05-20 08:27:17.915277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f3c04ef3e09'
down_revision = '6e3bf4d31e52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
